### ISSUE TITLE
新增pb协议使用时报错

### ISSUE THREAD

**Issue by bluesky0521** [huahua132/skynet_fly_demo#1]
在\proto\game.proto写：
```
message testpbcast{

}
```

在\table\table_plug.lua中注册proto并打印所有已注册消息，并在游戏开始广播时却报错了:

```
function M.init(instance)
	g_instance = instance
	local t = pb_netpack.load('./proto')
	for name, _ in pairs(t) do
		log.info("load proto:", name, " true or false:", res)
	end
end

....


local function game_start()
		m_instance:broad_cast_msg(m_table_id, '.game.testpbcast', {})
		...
end
```

报错内容：

>  [:00000012][20231122 13:47:07 61][error][room_game_table_m][../../skynet_fly/lualib/utils/net/util_net_base.lua:24]pb_netpack.pack err  17:1 .game.testpbcast encode not exists 17:1

日志显示消息已经注册过了：

>[:00000012][20231122 14:02:53 46][info][room_game_table_m][.//lualib/table/table_plug.lua:31]load proto: .game.testpbcast  true or false: true

在skynet_fly_demo\skynet_fly\lualib\netpack\pb_netpack.lua增加：
```
function M.getmap()
	return g_loaded
end
```
然后在广播前再次打印确认注册过了消息：
```
local function game_start()
		local t = pb_netpack.getmap()
		for name, res in pairs(t) do
			log.info("load proto:", name, " true or false:", res)
		end
		m_instance:broad_cast_msg(m_table_id, '.game.testpbcast', {})
                ...
end
```

运行结果还是如此：

> [:00000012][20231122 14:12:49 74][info][room_game_table_m][.//lualib/table/table_plug.lua:128]load proto: .game.testpbcast  true or false: true
> [:00000012][20231122 14:12:49 75][error][room_game_table_m][../../skynet_fly/lualib/utils/net/util_net_base.lua:24]pb_netpack.pack err  17:1 .game.testpbcast encode not exists 17:1

**Comment by huahua132** [comment]
m_instance:broad_cast_msg(m_table_id, '.game.testpbcast', {})
修改成
m_instance:broad_cast_msg( '.game.testpbcast', {})
即可
