### ISSUE TITLE
登录token生效时间问题

### ISSUE THREAD

**Issue by ych411521894** [huahua132/skynet_fly_demo#12]
一开始登录的时候没有问题，但是大概过了一段时间，机会出现错误Not acceptable by nbf，我看了下大概问题是body.nbf判断是否生效是os.time(),而初始化是time_util.time(),这两个时间流逝是不是有问题

**Comment by huahua132** [comment]
你用了fasttime.sh么，os.time()是系统时间，time_util.time()是skynet底层维护的时间，不用fasttime的话，os.time()=time_util.time
os.time()不受 fasttime.sh加速时间影响

**Comment by ych411521894** [comment]
> 你用了fasttime.sh么，os.time()是系统时间，time_util.time()是skynet底层维护的时间，不用fasttime的话，os.time()=time_util.time os.time()不受 fasttime.sh加速时间影响

我看过你的log有加速功能，但是我没用过

**Comment by huahua132** [comment]
![5c00afb08f1fb18ca990f87b6efdacd3](https://github.com/user-attachments/assets/bebcc3f4-fad7-42a1-a460-205fef8b8868)
你可以在这里加打印，看看什么情况

**Comment by ych411521894** [comment]
function M.skynet_int_time()
	skynet = skynet or require "skynet"
	if not starttime then
		starttime = math.floor(skynet.starttime() * 100)
	end
	return skynet.now() + starttime
end

--秒时间戳
function M.time()
	return math.floor(M.skynet_int_time() / 100)
end
这里你应该写错了，不应该是skynet.now而是skynet.time,now是当前时间戳+启动时间，双倍时间了，而应该给是skynet.time，服务器启动了多少时间吧

**Comment by ych411521894** [comment]
所以会出现有效时间一直大于os.time的情况

**Comment by huahua132** [comment]
```
function skynet.time()
	return skynet.now()/100 + (starttime or skynet.starttime())
end
```

**Comment by huahua132** [comment]
没写错，skynet.time也是这样实现的

**Comment by ych411521894** [comment]
> 没写错，skynet.time也是这样实现的

skynet这样写没问题，你不能这样用，skynet.now是启动了多少时间，你这里的skynet.time已经加上了一次starttime，你这里再加了一次，2次了

**Comment by huahua132** [comment]
nbf 是生效时间，你可以加打印看看token创建时的生效时间和校验时的生效时间是否一致

**Comment by huahua132** [comment]
```lua
local starttime
--整型的skynet_time 
function M.skynet_int_time()
	skynet = skynet or require "skynet"
	if not starttime then
		starttime = math.floor(skynet.starttime() * 100)
	end
	return skynet.now() + starttime
end

--秒时间戳
function M.time()
	return math.floor(M.skynet_int_time() / 100)
end

function skynet.time()
	return skynet.now()/100 + (starttime or skynet.starttime())
end
```

**Comment by huahua132** [comment]
我并不是基于skynet.time加的

**Comment by ych411521894** [comment]
你这里skynet.time()是不是skynet.now()/100 + (starttime or skynet.starttime())，然后调用skynet_int_time的时候公式是skynet.now()/100 + (starttime or skynet.starttime())+starttime，

**Comment by huahua132** [comment]
skynet_int_time 是 skynet.now() + starttime
你咋看出来是 skynet.now()/100 + (starttime or skynet.starttime())+starttime  ？？？

**Comment by ych411521894** [comment]
我恍惚了

**Comment by huahua132** [comment]
```
	log.info("time_util.time()", time_util.time())
	log.info("skynet.time()", skynet.time())
	log.info("os.time()", os.time())
```
![6cd11b1aa9e668ffb2e151a8c76a68b8](https://github.com/user-attachments/assets/8fcaa714-a5a9-4cc1-b95e-2c2500215182)

**Comment by huahua132** [comment]
你具体打印下，创建token的时间和验证token失败的地方，才能确认问题

**Comment by ych411521894** [comment]
> log.info("time_util.time()", time_util.time())
> 	log.info("skynet.time()", skynet.time())
> 	log.info("os.time()", os.time())

好的。。我打印看看应该容易复现的

**Comment by ych411521894** [comment]
> 你具体打印下，创建token的时间和验证token失败的地方，才能确认问题

Not acceptable by nbf:1727589221   1727589222

**Comment by ych411521894** [comment]
Not acceptable by nbf:1727589221   1727589222 差了1秒，应该是精度问题,前面的os.time,后面time_util.time，

**Comment by huahua132** [comment]
签发token那可以考虑改成用系统时间

**Comment by ych411521894** [comment]
> 签发token那可以考虑改成用系统时间

好的,大佬

**Comment by huahua132** [comment]
已改为系统时间
