### ISSUE TITLE
完全跟着docker部署走，但是配置mysql的时候会报错

### ISSUE THREAD

**Issue by hhn12138** [huahua132/skynet_fly_demo#3]
mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '123456';
ERROR 1524 (HY000): Plugin 'mysql_native_password' is not loaded
请问大神应该如何解决

**Comment by huahua132** [comment]
可以试试用这个命令启动mysql镜像`docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=123456 -d mysql:latest --default-authentication-plugin=mysql_native_password`

**Comment by huahua132** [comment]
直接安装mysql5.6吧，我试了一下也没了，估计是最新的镜像没有加载这个插件了
docker run --net="host" -d --name=mysql_container -e MYSQL_ROOT_PASSWORD=123456 mysql:5.6

**Comment by eeeEzreal** [comment]
同问

**Comment by huahua132** [comment]
用5.6也不行么？

**Comment by padoruuu** [comment]
`[:0000001e][20240609 07:02:22 68]lua call [1d to :1e : 31 msgsz = 5] error : [31m../../skynet_fly/skynet/lualib/skynet.lua:987: ../../skynet_fly/skynet/lualib/skynet.lua:452: ../../skynet_fly/skynet/lualib/skynet/queue.lua:20: ../../skynet_fly/skynet/lualib/skynet/queue.lua:20: ...skynet_fly/lualib/skynet-fly/client/contriner_client.lua:184: not svr admin
stack traceback:
	[C]: in function 'assert'
	...skynet_fly/lualib/skynet-fly/client/contriner_client.lua:184: in upvalue 'get_name_balance'
	...skynet_fly/lualib/skynet-fly/client/contriner_client.lua:532: in function 'skynet-fly.client.contriner_client.balance_call_by_name'
	(...tail calls...)
	...fly/lualib/skynet-fly/db/ormadapter/ormadapter_mysql.lua:199: in function 'skynet-fly.db.ormadapter.ormadapter_mysql.builder'
	../../skynet_fly/lualib/skynet-fly/db/orm/ormtable.lua:545: in function <../../skynet_fly/lualib/skynet-fly/db/orm/ormtable.lua:535>
	[C]: in function 'xpcall'
	../../skynet_fly/skynet/lualib/skynet/queue.lua:34: in field '_queue'
	../../skynet_fly/lualib/skynet-fly/db/orm/ormtable.lua:555: in function 'skynet-fly.db.orm.ormtable.builder'
	./orm_entity/roles_entity.lua:18: in function 'orm_entity.roles_entity.init'
	[C]: in function 'xpcall'
	../../skynet_fly/skynet/lualib/skynet/queue.lua:34: in upvalue 'queue'
	../../skynet_fly/module/orm_table_m.lua:161: in upvalue 'f'
	../../skynet_fly/skynet/lualib/skynet.lua:375: in function <../../skynet_fly/skynet/lualib/skynet.lua:374>
stack traceback:
	[C]: in function 'assert'
	../../skynet_fly/skynet/lualib/skynet/queue.lua:20: in function <../../skynet_fly/skynet/lualib/skynet/queue.lua:12>
	(...tail calls...)
	../../skynet_fly/lualib/skynet-fly/db/orm/ormtable.lua:555: in function 'skynet-fly.db.orm.ormtable.builder'
	./orm_entity/roles_entity.lua:18: in function 'orm_entity.roles_entity.init'
	[C]: in function 'xpcall'
	../../skynet_fly/skynet/lualib/skynet/queue.lua:34: in upvalue 'queue'
	../../skynet_fly/module/orm_table_m.lua:161: in upvalue 'f'
	../../skynet_fly/skynet/lualib/skynet.lua:375: in function <../../skynet_fly/skynet/lualib/skynet.lua:374>
stack traceback:
	[C]: in function 'assert'
	../../skynet_fly/skynet/lualib/skynet/queue.lua:20: in function <../../skynet_fly/skynet/lualib/skynet/queue.lua:12>
	(...tail calls...)
	../../skynet_fly/module/orm_table_m.lua:161: in upvalue 'f'
	../../skynet_fly/skynet/lualib/skynet.lua:375: in function <../../skynet_fly/skynet/lualib/skynet.lua:374>
stack traceback:
	[C]: in function 'assert'
	../../skynet_fly/skynet/lualib/skynet.lua:987: in function 'skynet.dispatch_message'[0m`

大神这个要怎么解决,启动就这样了

**Comment by huahua132** [comment]
not svr admin
数据库没连上的原因

**Comment by huahua132** [comment]
最新，已经修复了，load_mod 的 instance_name 没有填，所以索引不到 admin

**Comment by eeeEzreal** [comment]
我解决了。
在[mysqld]设置mysql_native_password=ON，
改完my.ini后用管理员身份打开命令提示符重启mysl即可。然后

net stop mysql
net start mysql
mysql -uroot -p
-- 输入密码
alter user 'root'@'localhost' identified with mysql_native_password;
alter user 'root'@'localhost' identified by '123456';

这样就可以了，你试试

**Comment by eeeEzreal** [comment]
如果安装包没有my.ini，就自己新建一个配置完再添上mysql_native_password=ON就好了

**Comment by huahua132** [comment]
cc
