### ISSUE TITLE
测试错误日志上报报错

### ISSUE THREAD

**Issue by bytemode** [huahua132/skynet_fly_demo#4]
[:00000010][20240620 13:38:41 53][info][web_agent_m][./router_group/warnlog_router.lua:16]"warnlog_router:" {
	[1] = "[admin_server][1][:0000000a][20240620 12:21:00 75][fatal][main][./main.lua:23]"测试错误日志上报:" "[20240620 12:21:00" 
[admin_server][1][:00000021][20240620 12:21:11 01]lua call [20 to :21 : 148 msgsz = 4788] error : [31m../../skynet_fly/skynet/lualib/skynet.lua:987: ../../skynet_fly/skynet/lualib/skynet.lua:452: ./module/monitor_m.lua:120: attempt to perform arithmetic on a nil value (field 'task')
stack traceback:
	./module/monitor_m.lua:120: in upvalue 'func'
	../../skynet_fly/skynet/lualib/skynet.lua:890: in upvalue 'f'
	../../skynet_fly/skynet/lualib/skynet.lua:402: in function <../../skynet_fly/skynet/lualib/skynet.lua:374>
stack traceback:
	[C]: in function 'assert'
	../../skynet_fly/skynet/lualib/skynet.lua:987: in function 'skynet.dispatch_message'[0m

**Comment by bytemode** [comment]
[admin_server][1][:00000021][20240620 12:42:04 77]lua call [20 to :21 : 1099 msgsz = 6870] error : [31m../../skynet_fly/skynet/lualib/skynet.lua:987: ../../skynet_fly/skynet/lualib/skynet.lua:452: ./module/monitor_m.lua:103: attempt to perform arithmetic on a nil value (local 'mem')
stack traceback:
	./module/monitor_m.lua:103: in upvalue 'func'
	../../skynet_fly/skynet/lualib/skynet.lua:890: in upvalue 'f'
	../../skynet_fly/skynet/lualib/skynet.lua:402: in function <../../skynet_fly/skynet/lualib/skynet.lua:374>
stack traceback:
	[C]: in function 'assert'
	../../skynet_fly/skynet/lualib/skynet.lua:987: in function 'skynet.dispatch_message'[0m
[admin_server][1][:00000021][20240620 12:43:08 01]lua call [20 to :21 : 1139 msgsz = 6870] error : [31m../../skynet_fly/skynet/lualib/skynet.lua:987: ../../skynet_fly/skynet/lualib/skynet.lua:452: ./module/monitor_m.lua:103: attempt to perform arithmetic on a nil value (local 'mem')
stack traceback:
	./module/monitor_m.lua:103: in upvalue 'func'
	../../skynet_fly/skynet/lualib/skynet.lua:890: in upvalue 'f'
	../../skynet_fly/skynet/lualib/skynet.lua:402: in function <../../skynet_fly/skynet/lualib/skynet.lua:374>
stack traceback:
	[C]: in function 'assert'
	../../skynet_fly/skynet/lualib/skynet.lua:987: in function 'skynet.dispatch_message'[0m
[admin_server][1][:00000021][20240620 12:44:10 89]lua call [20 to :21 : 1182 msgsz = 6870] error : [31m../../skynet_fly/skynet/lualib/skynet.lua:987: ../../skynet_fly/skynet/lualib/skynet.lua:452: ./module/monitor_m.lua:103: attempt to perform arithmetic on a nil value (local 'mem')
stack traceback:
	./module/monitor_m.lua:103: in upvalue 'func'
	../../skynet_fly/skynet/lualib/skynet.lua:890: in upvalue 'f'
	../../skynet_fly/skynet/lualib/skynet.lua:402: in function <../../skynet_fly/skynet/lualib/skynet.lua:374>
stack traceback:
	[C]: in function 'assert'
	../../skynet_fly/skynet/lualib/skynet.lua:987: in function 'skynet.dispatch_message'[0m
[admin_server][1][:00000021][20240620 12:45:09 92]lua call [20 to :21 : 1211 msgsz = 6871] error : [31m../../skynet_fly/skynet/lualib/skynet.lua:987: ../../skynet_fly/skynet/lualib/skynet.lua:452: ./module/monitor_m.lua:103: attempt to perform arithmetic on a nil value (local 'mem')
stack traceback:
	./module/monitor_m.lua:103: in upvalue 'func'
	../../skynet_fly/skynet/lualib/skynet.lua:890: in upvalue 'f'
	../../skynet_fly/skynet/lualib/skynet.lua:402: in function <../../skynet_fly/skynet/lualib/skynet.lua:374>

**Comment by huahua132** [comment]
已解决
