### ISSUE TITLE
后台登录报错handle_response err

### ISSUE THREAD

**Issue by bytemode** [huahua132/skynet_fly_demo#5]
[:00000011][20240620 13:35:41 41][error][web_agent_m][./model/model_user.lua:30]"err password" 
[:00000011][20240620 13:35:41 42][info][web_agent_m][...ynet_fly/lualib/skynet-fly/web/middleware/logger_mid.lua:46]"[http ACCESS] 2024/06/20 - 13:35:41 | 200 | 0.010 |             nil | POST    /user/login" 
[:00000011][20240620 13:35:44 95][info][web_agent_m][./middleware/token_auth_mid.lua:58]"token_auth_mid:" "/user/handshake" true 
[:00000011][20240620 13:35:44 95][error][web_agent_m][../../skynet_fly/module/web_agent_m.lua:164]"handle_response err " "./router_group/user_router.lua:64: not challenge
stack traceback:
	[C]: in function 'assert'
	./router_group/user_router.lua:64: in field '?'
	../../skynet_fly/lualib/skynet-fly/web/context_web.lua:53: in function 'skynet-fly.web.context_web.next'
	./middleware/permission_mid.lua:25: in field '?'
	../../skynet_fly/lualib/skynet-fly/web/context_web.lua:53: in function 'skynet-fly.web.context_web.next'
	./middleware/token_auth_mid.lua:63: in field '?'
	../../skynet_fly/lualib/skynet-fly/web/context_web.lua:53: in function 'skynet-fly.web.context_web.next'
	./app.lua:20: in field '?'
	../../skynet_fly/lualib/skynet-fly/web/context_web.lua:53: in function 'skynet-fly.web.context_web.next'
	...ynet_fly/lualib/skynet-fly/web/middleware/logger_mid.lua:32: in field '?'
	../../skynet_fly/lualib/skynet-fly/web/context_web.lua:53: in function 'skynet-fly.web.context_web.next'
	../../skynet_fly/lualib/skynet-fly/web/engine_web.lua:104: in function 'app.dispatch'
	(...tail calls...)
	../../skynet_fly/lualib/skynet-fly/web/handle_web.lua:72: in function <../../skynet_fly/lualib/skynet-fly/web/handle_web.lua:61>
	[C]: in function 'xpcall'
	../../skynet_fly/lualib/skynet-fly/preload.lua:28: in function 'x_pcall'
	../../skynet_fly/module/web_agent_m.lua:162: in function <../../skynet_fly/module/web_agent_m.lua:125>
	(...tail calls...)
	../../skynet_fly/lualib/skynet-fly/utils/skynet_util.lua:33: in upvalue 'f'
	../../skynet_fly/skynet/lualib/skynet.lua:402: in function <../../skynet_fly/skynet/lualib/skynet.lua:374>"

**Comment by huahua132** [comment]
正常握手错误
