### ISSUE TITLE
chinnese_chess启动报错

### ISSUE THREAD

**Issue by bytemode** [huahua132/skynet_fly_demo#6]
[:0000001b][20240620 12:12:59 68][error][room_game_alloc_m][../../skynet_fly/lualib/skynet-fly/timer.lua:32]"time_out_func err " "../../skynet_fly/skynet/lualib/skynet/queue.lua:20: ../../skynet_fly/module/room_game_alloc_m.lua:157: assertion failed!
stack traceback:
	[C]: in function 'assert'
	../../skynet_fly/module/room_game_alloc_m.lua:157: in function <../../skynet_fly/module/room_game_alloc_m.lua:156>
	[C]: in function 'xpcall'
	../../skynet_fly/skynet/lualib/skynet/queue.lua:34: in function <../../skynet_fly/skynet/lualib/skynet/queue.lua:24>
	(...tail calls...)
	../../skynet_fly/module/room_game_alloc_m.lua:223: in function <../../skynet_fly/module/room_game_alloc_m.lua:217>
	[C]: in function 'xpcall'
	../../skynet_fly/lualib/skynet-fly/preload.lua:28: in function 'x_pcall'
	../../skynet_fly/lualib/skynet-fly/timer.lua:30: in upvalue 'execute_call_back'
	../../skynet_fly/lualib/skynet-fly/timer.lua:47: in upvalue 'time_out_func'
	../../skynet_fly/lualib/skynet-fly/timer.lua:60: in upvalue 'func'
	../../skynet_fly/skynet/lualib/skynet.lua:890: in upvalue 'f'
	../../skynet_fly/skynet/lualib/skynet.lua:402: in function <../../skynet_fly/skynet/lualib/skynet.lua:374>
stack traceback:

**Comment by bytemode** [comment]
![image](https://github.com/huahua132/skynet_fly_demo/assets/8018919/b6f8b6ec-a3b6-47fb-9115-149845b85ca5)

**Comment by huahua132** [comment]
已解决
